### ISSUE TITLE
PyCon US 2020

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#1017]
```yaml
- title: PyCon US 2020
  dir: pycon-us-2020
  youtube_list:
    - https://www.youtube.com/playlist?list=UUMjMBMGt0WJQLeluw6qNJuA
  related_urls:  
    - label: Conference schedule
      url: https://us.pycon.org/2020/online/
  language: eng
  dates:
    begin: 2020-04-15
    end: 2020-04-23
    default: 2020-04-17
  issue: 1017
  minimal_download: True
  tags: []
```
