### ISSUE TITLE
SciPy 2020

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#1030]
```yaml
- title: SciPy 2020
  dir: scipy-2020
  youtube_list:
    - https://www.youtube.com/playlist?list=PLYx7XA2nY5GfhekhCPLpA0NImFm2wNvSD
    - https://www.youtube.com/playlist?list=PLYx7XA2nY5GfY4WWJjG5cQZDc7DIUmn6Z
    - https://www.youtube.com/playlist?list=PLYx7XA2nY5GejOB1lsvriFeMytD1-VS1B
    - https://www.youtube.com/playlist?list=PLYx7XA2nY5GcTCOoxtlqebZExBfwXj58o
    - https://www.youtube.com/playlist?list=PLYx7XA2nY5GezZTawXyl76LqVf3qbn-5E
    - https://www.youtube.com/playlist?list=PLYx7XA2nY5GdNCo46AUhZ8RwlshVmgZTa
    - https://www.youtube.com/playlist?list=PLYx7XA2nY5GdcCuhzg1G7Zt4apRnIn-u9
  related_urls:  
    - label: Conference schedule
      url: https://www.scipy2020.scipy.org/schedule
  language: eng
  dates:
    begin: 2020-07-06
    end: 2020-07-12
    default: 2020-07-06
  issue: 1030
  minimal_download: True
  tags: []
```
