### ISSUE TITLE
PyCon AU 2021

### ISSUE THREAD

**Issue by glasnt** [pyvideo/data#1070]
```
events: 
- title: PyCon AU 2021
  dir: pycon-au-2021
  issue: 1070
  youtube_list:
   - https://www.youtube.com/playlist?list=PLs4CJRBY5F1LKN2ISCse415LW5FZEjDX2
  related_urls:
  - label: Conference schedule
    url: https://2021.pycon.org.au/program/
  language: eng
  dates:
    begin: 2021-09-10
    end: 2021-09-11
    default: 2021-09-11
  tags:

```
