### ISSUE TITLE
PyData Miami 2019

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#804]
```yaml
- title: PyData Miami 2019
  dir: pydata-miami-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLGVZCDnMOq0qtkoXglrDC6pS8NvY94QQw
  related_urls:  
    - label: Conference schedule
      url: https://pydata.org/miami2019/schedule/
  language: eng
  dates:
    begin: 2019-01-09
    end: 2019-01-11
    default: 2019-01-09
  issue: 804
  minimal_download: True
  tags: 'pydata'
```
