### ISSUE TITLE
PyData Amsterdam 2019

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#812]
```yaml
- title: PyData Amsterdam 2019
  dir: pydata-amsterdam-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLGVZCDnMOq0q7_6SdrC2wRtdkojGBTAht
  related_urls:  
    - label: Conference schedule
      url: https://pydata.org/amsterdam2019/schedule/
  language: eng
  dates:
    begin: 2019-05-10
    end: 2019-05-12
    default: 2019-05-10
  issue: 812
  minimal_download: True
  tags: ['pydata']
```
