### ISSUE TITLE
PyData London 2019

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#835]
```yaml
- title: PyData London 2019
  dir: pydata-london-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLGVZCDnMOq0ocea1dd0it7jX7HgvZCjSW
  related_urls:  
    - label: Conference schedule
      url: https://pydata.org/london2019/schedule/
  language: eng
  dates:
    begin: 2019-07-12
    end: 2019-07-14
    default: 2019-07-13
  issue: 835
  minimal_download: True
  tags: []
```
