### ISSUE TITLE
PyLondinium 2019

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#838]
```yaml
- title: PyLondinium 2019
  dir: pylondinium-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLWsDEQH0HiPalyM87r_HFIiD53n2k_LMZ
  related_urls:  
    - label: Conference schedule
      url: https://pylondinium.org/schedule.html
  language: eng
  dates:
    begin: 2019-06-14
    end: 2019-06-16
    default: 2019-06-14
  issue: 838
  minimal_download: True
  tags: []
```
