### ISSUE TITLE
PyDay NEA 2019

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#841]
```yaml
- title: PyDay NEA 2019
  dir: pyday-nea-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLJwVSKQZpWB1HQUp443wVdMErhtXuwzsc
  related_urls:  
    - label: Conference schedule
      url: https://eventos.python.org.ar/events/pydaynea2019/
  language: spa
  dates:
    begin: 2019-06-29
    end: 2019-06-29
    default: 2019-06-29
  issue: 841
  minimal_download: False
  tags: []
```
