### ISSUE TITLE
PyCon Latam 2019 minimal download

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#878]
```yaml
- title: PyCon Latam
  dir: pycon-latam-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLILBUtFSYL-9c1ejQulv5YQaifb0HSSPH
  related_urls:  
    - label: Conference schedule
      url: https://www.pylatam.org/en/full-schedule/
  language: spa
  dates:
    begin: 2019-08-29
    end: 2019-08-31
    default: 2019-06-29
  issue: 878
  minimal_download: True
  tags: []
```
