### ISSUE TITLE
SciPy Latin America 2019

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#880]
```yaml
- title: SciPy Latin America 2019
  dir: scipy-la-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLfVc-mR8AkU2P6DT7ySZP3JfbQlic0mQh
  related_urls:  
    - label: Conference schedule
      url: https://conf.scipyla.org/en/program/schedule/
  language: spa
  dates:
    begin: 2019-10-08
    end: 2019-10-10
    default: 2019-10-08
  issue: 880
  minimal_download: True
  tags: []
```
