### ISSUE TITLE
PyData New York City 2019 

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#913]
```yaml
- title: PyData New York City 2019 
  dir: pydata-new-york-city-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLGVZCDnMOq0pwoOqsaA87cAoNM4MWr51M
  related_urls:  
    - label: Conference schedule
      url: https://pydata.org/nyc2019/schedule/
  language: eng
  dates:
    begin: 2019-11-04
    end: 2019-11-06
    default: 2019-11-04
  issue: 
  minimal_download: True
  tags: []
```
