### ISSUE TITLE
PyData Austin 2019

### ISSUE THREAD

**Issue by akielbowicz** [pyvideo/data#923]
```yaml
- title: PyData Austin 2019
  dir: pydata-austin-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLGVZCDnMOq0r9UZJ-Afvv9jgZQ1JIvBTC
  related_urls:
  - label: Conference schedule
    url: https://pydata.org/austin2019/schedule/
  language: eng
  dates:
    begin: 2019-12-07
    end: 2019-12-08
    default: 2019-12-07
  issue: 923
  tags:

  minimal_download: true
  overwrite:
    # all: true # takes precedence over add_new_files and existing_files_fields
    add_new_files: true
```
