### ISSUE TITLE
PyData DC 2016

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#94]
Not ready yet for scraping.

``` yaml
- title: PyData DC 2016
  dir: pydata-dc-2016
  youtube_list: https://www.youtube.com/playlist?list=PLGVZCDnMOq0qLoYpkeySVtfdbQg1A_GiB
  issue: 94
  language: eng
  web: http://pydata.org/dc2016
```
